spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:test}
      repositories:
      enabled: true

  server:
    port: ${SERVER_PORT:8090}
  profiles: prod

proxy: proxySet
check: true
socksHost: socksProxyHost
host: 127.0.0.1
socksPort: socksProxyPort
port: 9150
botUserName: SumkiRomanBot
token: ${TOKEN_BOT:token}
checkFlag: added
pathThePhoto: C:/woman_bag/
typeFilePng: .png
typeFileMp4: .mp4

